#!/bin/sh

system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then

  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  if [ -f "$HOME/.Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --global
  fi

  if [ ! -d "$HOME/.oh-my-zsh" ]; then
    echo "Installing oh-my-zsh"
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    rm "$HOME/.zshrc" && mv "$HOME/.zshrc.pre-oh-my-zsh" "$HOME/.zshrc"
  fi

  if command -v vim >/dev/null 2>&1; then
    echo "Bootstraping Vim"
    curl --create-dirs -fsSLo "$HOME/.vim/autoload/plug.vim https://raw.github.com/junegunn/vim-plug/master/plugvim"
    vim '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+qall'
  fi

  if [ ! -d "$HOME/.tmux/plugins/tpm" ]; then
    echo "Installing Tmux Plugin Manager and plugins"
    git clone https://github.com/tmux-plugins/tpm "$HOME/.tmux/plugins/tpm" && $HOME/.tmux/plugins/tpm/bin/install_plugins
  fi

  if [ ! -d "$HOME/miniconda" ]; then
    echo "Installing Miniconda"
    curl -fsSL https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -o "$HOME/miniconda.sh"
    bash "$HOME/miniconda.sh" -b
    rm "$HOME/miniconda.sh"
    conda create -n pynvim -c conda-forge pynvim
  fi

fi
